# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jamii', '0006_profile_neighbourhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='neighbourhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jamii.Neighbourhood'),
        ),
    ]
